### ISSUE TITLE
Requesting theos dependencies

### ISSUE THREAD

**Issue by SkittybIock** [ElectraJailbreak/electratools#12]
I always like to have theos on device. It'd be great to have it working.

- git
- perl
- make
- clang
- ldid
- etc.

(and the rest from theos dependencies and iOS toolchain)

**Comment by coolstar** [comment]
git, make and ldid have been approved for this repo

perl will be on my own repo, and clang/ld/cctools will be on bigboss soon

**Comment by SkittybIock** [comment]
Well. Git is unable to clone and perl has yet to be updated. I can live without git, but perl is really required for theos. Should I expect an update or do I have to figure out how to do it myself?

**Comment by 1nternist** [comment]
I agree sir.  I have compiled a few tools myself, but I have never compiled perl to tell you the truth.  If I knew what environment variables  Coolstar used to compile 5.22.0 I could probably figure out how to port it to arm64.  That said, I have the distinct feeling Coolstar is far too busy with the Electra upgrade and support to dedicate any substantial amount of time updating perl at this time. 

Cheers,

dc1nternist

**Comment by v0lumehi** [comment]
I'm experiencing this issue too after trying to use theos with your provided perl package. Is there a way to fix this? I know that this package is being maintained at your own repo but I couldn't find it on github to report it so I am writing here. Can you reopen this issue again?

**Comment by v0lumehi** [comment]
@GeoSn0w will you do a video on this? 😀

**Comment by v0lumehi** [comment]
IMO this should be fixed. The perl package is installed automatically with the jailbreak so it should work. Providing broken packages in a repo is not that good. If it's not possible to fix this then the workaround should be clearly documented at the right place.

**Comment by 1nternist** [comment]
Awesome find Shittyblock! I also confirm that perl 5.26.1 from http://repo.bingner.com works with iOS 11 and theos. I am also updating libdpkg-perl and libtimedate-perl from my repo to be compatible with dpkg-scanpackages so on device Cydia repos such as CyGit from my repo will be functional again. 

I’ll have this finished later today. 

Cheers!

dc1nternist
