### ISSUE TITLE
Can we have these tools?

### ISSUE THREAD

**Issue by meeeo** [ElectraJailbreak/electratools#2]
If you mean it, can we have these tools that I always use in Linux:

- htop
- lnav 
- ranger
- joe 
- autossh
- mosh
- corkscrew
- tsocks
- asciinema
- nmap
- bettercap   https://github.com/evilsocket/bettercap-ng#cross-compiling
- dnscrypt (server/client)
- tcpdump /  tshark
- screen / tmux
- sshfs
- wget
- docker the container
- fish the shell
- rsync

Really exciting for seeing them on a iDevice.

**Comment by Favna** [comment]
totally behind htop, wget and tmux. To a avoid creating a whole slew of issues, would you mind adding `curl` to your list @meeeo ?

**Comment by jailbreakiphone** [comment]
Maybe lftp too!

**Comment by sohsatoh** [comment]
yeah, i need rsync to back up some files...

**Comment by parrotgeek1** [comment]
@meeeo  sshfs and docker won't work (no kernel access so no FUSE or containers) but all the other ones should be possible

**Comment by coolstar** [comment]
Approved Packages:

1. autossh
2. screen
3. rsync
4. wget

Expect them to be up

**Comment by coolstar** [comment]
wget is up

**Comment by FaZeIlLuMiNaTi** [comment]
can we get top too?
