### ISSUE TITLE
Apt-get update cant seem to drop privileges

### ISSUE THREAD

**Issue by dallasgroot** [ElectraJailbreak/electratools#25]
Ever since first launch of cydia, I cannot seem to getany of my sources to actually load anything (besides oscreatix. 

Here is an example of the output I am getting via ssh:

`Dallass-iPhone:~ root# apt-get update
Ign:1 http://apt.thebigboss.org/repofiles/cydia stable InRelease
Ign:2 http://beta.sparkservers.co.uk ./ InRelease                              
Get:3 http://apt.thebigboss.org/repofiles/cydia stable Release [472 B]         
Get:4 http://beta.sparkservers.co.uk ./ Release [176 B]                        
Ign:5 http://apt.modmyi.com stable InRelease                                   
Ign:6 https://seiterseiter.github.io ./ InRelease                              
Ign:7 http://beta.sparkservers.co.uk ./ Release.gpg                            
Get:8 http://apt.modmyi.com stable Release [385 B]                             
Get:9 http://apt.thebigboss.org/repofiles/cydia stable Release.gpg [181 B]     
Ign:10 https://repo.dynastic.co/beta ./ InRelease                              
Get:11 https://seiterseiter.github.io ./ Release [186 B]                       
Ign:12 http://kdog0598.github.com ./ InRelease                                 
Ign:13 http://junesiphone.com/supersecret ./ InRelease                         
Ign:14 http://remyla.yourepo.com ./ InRelease                                  
Ign:15 http://ethanrdoesmc.tk/repo ./ InRelease                                
Get:16 http://apt.modmyi.com stable Release.gpg [181 B]                        
Ign:17 http://beta.sparkservers.co.uk ./ Packages                              
Ign:18 https://seiterseiter.github.io ./ Release.gpg                           
Get:17 http://beta.sparkservers.co.uk ./ Packages [2208 B]                     
Ign:19 https://packix.ioscreatix.com ./ InRelease                              
Ign:20 https://repo.reedhaffner.com ./ InRelease                               
Ign:21 https://gmoran.me/repo ./ InRelease                                     
Ign:22 https://beta.laughingquoll.net/repo ./ InRelease                        
Ign:23 https://seiterseiter.github.io ./ Packages                              
Get:24 http://kdog0598.github.com ./ Release [218 B]                           
Get:25 http://ethanrdoesmc.tk/repo ./ Release [180 B]                          
Ign:26 https://repo.cpdigitaldarkroom.com ./ InRelease                         
Ign:27 https://repo.dynastic.co/beta ./ Release                                
Ign:28 http://junesiphone.com/supersecret ./ Release                           
Get:29 http://remyla.yourepo.com ./ Release                                    
Get:23 https://seiterseiter.github.io ./ Packages [474 B]                      
Ign:30 http://kdog0598.github.com ./ Release.gpg                               
Ign:31 https://cydia.hbang.ws ./ InRelease                                     
Ign:32 https://ib-soft.net/cydia/beta ./ InRelease                             
Ign:33 http://ethanrdoesmc.tk/repo ./ Release.gpg                              
Ign:34 https://electrarepo64.coolstar.org/substrate-shim ./ InRelease          
Get:35 https://gmoran.me/repo ./ Release [169 B]                               
Ign:36 http://kdog0598.github.com ./ Packages                                  
Get:37 https://beta.laughingquoll.net/repo ./ Release [198 B]                  
Ign:38 https://repo.dynastic.co/beta ./ Packages                               
Ign:39 https://electrarepo64.coolstar.org ./ InRelease                         
Ign:40 http://junesiphone.com/supersecret ./ Packages                          
Get:36 http://kdog0598.github.com ./ Packages [1804 B]                         
Get:41 https://repo.cpdigitaldarkroom.com ./ Release [188 B]                   
Ign:42 http://remyla.yourepo.com ./ Release.gpg                                
Ign:38 https://repo.dynastic.co/beta ./ Packages                               
Ign:43 http://ethanrdoesmc.tk/repo ./ Packages                                 
Get:44 https://cydia.hbang.ws ./ Release [654 B]                               
Ign:45 http://apt.saurik.com ios/1445.32 InRelease                             
Ign:46 https://gmoran.me/repo ./ Release.gpg                                   
Ign:47 https://beta.laughingquoll.net/repo ./ Release.gpg                      
Ign:38 https://repo.dynastic.co/beta ./ Packages                               
Get:43 http://ethanrdoesmc.tk/repo ./ Packages [2484 B]                        
Get:48 https://repo.reedhaffner.com ./ Release [186 B]                         
Get:40 http://junesiphone.com/supersecret ./ Packages [34.3 kB]                
Ign:38 https://repo.dynastic.co/beta ./ Packages                               
Ign:49 https://cydia.angelxwind.net ./ InRelease                               
Ign:50 https://repo.cpdigitaldarkroom.com ./ Release.gpg                       
Ign:51 http://remyla.yourepo.com ./ Packages                                   
Ign:52 https://beta.laughingquoll.net/repo ./ Packages                         
Get:53 https://cydia.hbang.ws ./ Release.gpg [488 B]                           
Err:38 https://repo.dynastic.co/beta ./ Packages                               
  HTTP/1.1 404 Not Found
Ign:54 https://ib-soft.net/cydia ./ InRelease                                  
Get:55 https://electrarepo64.coolstar.org/substrate-shim ./ Release [266 B]    
Get:56 https://packix.ioscreatix.com ./ Release [180 B]                        
Ign:57 https://gmoran.me/repo ./ Packages                                      
Get:52 https://beta.laughingquoll.net/repo ./ Packages [2010 B]                
Ign:58 https://repo.cpdigitaldarkroom.com ./ Packages                          
Get:51 http://remyla.yourepo.com ./ Packages                                   
Ign:9 http://apt.thebigboss.org/repofiles/cydia stable Release.gpg             
Get:59 https://electrarepo64.coolstar.org ./ Release [229 B]                   
Get:57 https://gmoran.me/repo ./ Packages [1422 B]                             
Get:58 https://repo.cpdigitaldarkroom.com ./ Packages [11.7 kB]                
Get:60 http://apt.thebigboss.org/repofiles/cydia stable/main iphoneos-arm Packages [1457 kB]
Ign:61 https://repo.reedhaffner.com ./ Release.gpg                             
Ign:62 https://electrarepo64.coolstar.org/substrate-shim ./ Release.gpg        
Ign:63 http://apt.saurik.com ios/1445.32 Release                               
Get:64 https://ib-soft.net/cydia/beta ./ Release [211 B]                       
Ign:65 https://electrarepo64.coolstar.org ./ Release.gpg                       
Get:66 https://cydia.angelxwind.net ./ Release [200 B]                         
Ign:16 http://apt.modmyi.com stable Release.gpg                                
Get:67 https://ib-soft.net/cydia ./ Release [196 B]                            
Get:68 http://apt.modmyi.com stable/main iphoneos-arm Packages [1941 kB]       
Ign:69 https://repo.reedhaffner.com ./ Packages                                
Ign:70 https://ib-soft.net/cydia/beta ./ Release.gpg                           
Ign:71 https://electrarepo64.coolstar.org/substrate-shim ./ Packages           
Ign:72 https://packix.ioscreatix.com ./ Release.gpg                            
Ign:73 https://ib-soft.net/cydia ./ Release.gpg                                
Ign:74 https://electrarepo64.coolstar.org ./ Packages                          
Ign:53 https://cydia.hbang.ws ./ Release.gpg                                   
Get:69 https://repo.reedhaffner.com ./ Packages [378 B]                        
Ign:75 http://apt.saurik.com ios/1445.32/main iphoneos-arm Packages            
Get:71 https://electrarepo64.coolstar.org/substrate-shim ./ Packages [452 B]   
Get:74 https://electrarepo64.coolstar.org ./ Packages [7268 B]                 
Get:76 https://cydia.hbang.ws ./ Packages [5706 B]                             
Ign:77 https://cydia.angelxwind.net ./ Release.gpg                             
Ign:78 https://ib-soft.net/cydia/beta ./ Packages                              
Ign:79 https://ib-soft.net/cydia ./ Packages                                   
Get:80 https://packix.ioscreatix.com ./ Packages [2528 B]                      
Get:78 https://ib-soft.net/cydia/beta ./ Packages [1111 B]                     
Ign:75 http://apt.saurik.com ios/1445.32/main iphoneos-arm Packages            
Ign:81 https://cydia.angelxwind.net ./ Packages                                
Get:79 https://ib-soft.net/cydia ./ Packages [954 B]                           
Get:81 https://cydia.angelxwind.net ./ Packages [9023 B]                       
Ign:75 http://apt.saurik.com ios/1445.32/main iphoneos-arm Packages            
Ign:75 http://apt.saurik.com ios/1445.32/main iphoneos-arm Packages            
Err:75 http://apt.saurik.com ios/1445.32/main iphoneos-arm Packages            
  POSIX: Connection refused
Fetched 3488 kB in 14s (246 kB/s)                                              
Reading package lists... Done
W: No sandbox user '_apt' on the system, can not drop privileges
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/beta.sparkservers.co.uk_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/seiterseiter.github.io_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/kdog0598.github.com_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/ethanrdoesmc.tk_repo_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/remyla.yourepo.com_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/gmoran.me_repo_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/beta.laughingquoll.net_repo_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/repo.cpdigitaldarkroom.com_._Release
W: GPG error: http://apt.thebigboss.org/repofiles/cydia stable Release: The following signatures were invalid: A9C96A37115894A23B894107694D17D38764B4F4
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/apt.thebigboss.org_repofiles_cydia_dists_stable_Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/repo.reedhaffner.com_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/electrarepo64.coolstar.org_substrate-shim_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/electrarepo64.coolstar.org_._Release
W: GPG error: http://apt.modmyi.com stable Release: The following signatures were invalid: EB22AD483B83E9A7460D86F387F92E166197E890
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/apt.modmyi.com_dists_stable_Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/ib-soft.net_cydia_beta_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/packix.ioscreatix.com_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/ib-soft.net_cydia_._Release
W: GPG error: https://cydia.hbang.ws ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5D3B26B3D58C7D91
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/cydia.hbang.ws_._Release
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/cydia.angelxwind.net_._Release
E: Failed to fetch https://repo.dynastic.co/beta/./Packages  HTTP/1.1 404 Not Found
E: Failed to fetch http://apt.saurik.com/dists/ios/1445.32/main/binary-iphoneos-arm/Packages  POSIX: Connection refused
E: Some index files failed to download. They have been ignored, or old ones used instead.`

Obviously the POSIX error is normal as it’s blocked. 

Here is the [cydia error](https://twitter.com/iamgroot11/status/970145468591173634)

IPhone 8 11.1.2
Electra b3-1.0.2 (no RC leakes)

Also, no to.panga installed as well as any other modifications either than LiberiOS which did nothing. 

APFS has also been successful on 1.0.1.

**Comment by dallasgroot** [comment]
It seems like apt-key is the main culprit! anyway someone can ssh into their phones and type `apt-key list` and tell me what the outcome is? because I keep getting:

`Last login: Wed Mar  7 10:10:48 on ttys000
Dallass-MacBook-Pro:~ dallasgroot$ ssh root@192.168.0.10
root@192.168.0.10's password: 
Dallass-iPhone:~ root# apt-key 
-sh: /usr/bin/apt-key: /bin/sh: bad interpreter: Operation not permitted
Dallass-iPhone:~ root# apt-key list
-sh: /usr/bin/apt-key: /bin/sh: bad interpreter: Operation not permitted
Dallass-iPhone:~ root# 


`

**Comment by AppleBetas** [comment]
@dallasgroot I get the same thing on my phone with working Cydia

**Comment by dallasgroot** [comment]
This is very strange! what about apt-get update? does it show errors like the last part?

**Comment by AppleBetas** [comment]
Apt-get just doesn't work because I haven't installed any packages to use it from the command line. Though at least because of above (apt-key), we now know that this appears to be a different issue than #23.

It looks like when its downloading the packages files, it doesn't actually receive anything, according to the filesize and md5sum from screenshots, at least. What APT packages do you have installed?

**Comment by dallasgroot** [comment]
exactly, which is leaving me to believe that either there is permission issues with /caches or....?

**Comment by dallasgroot** [comment]
[This is the cydia error (I'm sure you've seen this many times from me....](https://pbs.twimg.com/media/DXjFyj5VQAEtsuG.jpg:large)

**Comment by AppleBetas** [comment]
Hmm, what are the permissions on the directory and subdirectories of /var/lib/apt?

**Comment by dallasgroot** [comment]
<img width="473" alt="screen shot 2018-03-08 at 2 55 49 pm" src="https://user-images.githubusercontent.com/7484579/37181204-d7f4a5be-22e0-11e8-9270-8f890531e182.png">

**Comment by dallasgroot** [comment]
/var/ 777
/lib/ 777
/ap/t 777
 /extended_states 777
 /lists 777
     /(all .release files are 644
     /partial/ 700
        / apt.modmyi.com_dists_stable_Release.gpg 644
        /apt.thebigboss.org_repofiles_cydia_dists_stable_Release.gpg 644
        /cydia.hbang.ws_._Release.gpg 644
 /mirrors/ 777
   /partial/ 755
/periodic/ 755

**Comment by dallasgroot** [comment]
<img width="985" alt="screen shot 2018-03-08 at 3 20 26 pm" src="https://user-images.githubusercontent.com/7484579/37182021-41b5cab6-22e4-11e8-9fb7-1a1ea621cb79.png">
This is the release files inside` /lists` directory, these download just fine

**Comment by dallasgroot** [comment]
```
Dallass-iPhone:~ root# apt list --installed
Listing... DoneD
Flex3beta/stable,now 1:3~Beta46 iphoneos-arm [installed]
applist/stable,now 1.5.14 iphoneos-arm [installed]
apt7/stable,now 0.7.25.3-9 iphoneos-arm [installed]
apt7-key/stable,now 0.7.25.3-4 iphoneos-arm [installed]
apt7-lib/stable,now 0.7.25.3-16-coolstar iphoneos-arm [installed]
base/now 1-4 iphoneos-arm [installed,local]
bash/stable,now 4.4 iphoneos-arm [installed]
berkeleydb/stable,now 6.2.23 iphoneos-arm [installed]
bzip2/stable,now 1.0.6 iphoneos-arm [installed]
com.anemonetheming.anemone/stable,now 2.1.7-1 iphoneos-arm [installed]
com.chpwn.iconsupport/stable,now 1.11.0-1 iphoneos-arm [installed]
com.ex.libsubstitute/stable,now 0.0.5-coolstar iphoneos-arm [installed]
com.ioscreatix.intelix/stable,now 1.1.4 iphoneos-arm [installed]
com.ioscreatix.littlex/stable,now 1.3.6 iphoneos-arm [installed]
com.ioscreatix.silo/stable,now 1.0.0-4+debug iphoneos-arm [installed,automatic]
com.laughingquoll.noctisxi/stable,now 1.0.6.2 iphoneos-arm [installed,upgradable to: 1.0.8]
com.rpetrich.rocketbootstrap/stable,now 1.0.6 iphoneos-arm [installed]
com.spark.easyswitcherx/now 0.0.2 iphoneos-arm [installed,local]
com.spark.taptickeys/now 0.0.1-8+debug iphoneos-arm [installed,upgradable to: 3.0.3]
com.sticktron.darkmessages/stable,now 1.2.0-1 iphoneos-arm [installed]
coreutils/stable,now 8.28 iphoneos-arm [installed]
coreutils-bin/stable,now 8.28 iphoneos-arm [installed]
curl/stable,now 7.50.1-2 iphoneos-arm [installed]
cy+cpu.arm64/now 0 iphoneos-arm [installed,local]
cy+kernel.darwin/now 17.2.0 iphoneos-arm [installed,local]
cy+lib.corefoundation/now 1445.32 iphoneos-arm [installed,local]
cy+model.iphone/now 10.4 iphoneos-arm [installed,local]
cy+os.ios/now 11.1.2 iphoneos-arm [installed,local]
cydia/stable,now 1.1.30-coolstar4 iphoneos-arm [installed]
cydia-lproj/now 1.1.12 iphoneos-arm [installed,local]
darwintools/stable,now 1-6 iphoneos-arm [installed]
debianutils/stable,now 4.8.4 iphoneos-arm [installed]
diffutils/stable,now 3.6 iphoneos-arm [installed]
dpkg/stable,now 1.18.24 iphoneos-arm [installed]
findutils/stable,now 4.6 iphoneos-arm [installed]
firmware/now 11.1.2 iphoneos-arm [installed,local]
firmware-sbin/now 0-1 iphoneos-arm [installed,local]
gcrypt/stable,now 1.8.2 iphoneos-arm [installed]
gnupg/stable,now 1.4.22 iphoneos-arm [installed]
gnupg2/stable,now 2.2.3 iphoneos-arm [installed]
grep/stable,now 3.1 iphoneos-arm [installed]
gsc.3-gvenice/now 1 iphoneos-arm [installed,local]
gsc.720p/now 1 iphoneos-arm [installed,local]
gsc.accelerometer/now 1 iphoneos-arm [installed,local]
gsc.accessibility/now 1 iphoneos-arm [installed,local]
gsc.additional-text-tones/now 1 iphoneos-arm [installed,local]
gsc.air-drop-capability/now 1 iphoneos-arm [installed,local]
gsc.all-features/now 1 iphoneos-arm [installed,local]
gsc.allow-you-tube/now 1 iphoneos-arm [installed,local]
gsc.allow-you-tube-plugin/now 1 iphoneos-arm [installed,local]
gsc.ambient-light-sensor/now 1 iphoneos-arm [installed,local]
gsc.any-telephony/now 1 iphoneos-arm [installed,local]
gsc.armv6/now 1 iphoneos-arm [installed,local]
gsc.armv7/now 1 iphoneos-arm [installed,local]
gsc.assistant/now 1 iphoneos-arm [installed,local]
gsc.auto-focus-camera/now 1 iphoneos-arm [installed,local]
gsc.battery-current-capacity/now 41 iphoneos-arm [installed,local]
gsc.bluetooth/now 1 iphoneos-arm [installed,local]
gsc.bluetooth-le/now 1 iphoneos-arm [installed,local]
gsc.board-id/now 10 iphoneos-arm [installed,local]
gsc.camera-flash/now 1 iphoneos-arm [installed,local]
gsc.cellular-data/now 1 iphoneos-arm [installed,local]
gsc.cellular-telephony-capability/now 1 iphoneos-arm [installed,local]
gsc.chip-i-d/now 32789 iphoneos-arm [installed,local]
gsc.contains-cellular-radio/now 1 iphoneos-arm [installed,local]
gsc.device-class-number/now 1 iphoneos-arm [installed,local]
gsc.device-color/now 2 iphoneos-arm [installed,local]
gsc.device-enclosure-color/now 2 iphoneos-arm [installed,local]
gsc.device-supports-navigation/now 1 iphoneos-arm [installed,local]
gsc.device-supports-simplistic-road-mesh/now 1 iphoneos-arm [installed,local]
gsc.device-supports-tethering/now 1 iphoneos-arm [installed,local]
gsc.device-supports1080p/now 1 iphoneos-arm [installed,local]
gsc.device-supports3-d-imagery/now 1 iphoneos-arm [installed,local]
gsc.device-supports3-d-maps/now 1 iphoneos-arm [installed,local]
gsc.device-supports720p/now 1 iphoneos-arm [installed,local]
gsc.device-supports9-pin/now 1 iphoneos-arm [installed,local]
gsc.dictation/now 1 iphoneos-arm [installed,local]
gsc.display-mirroring/now 1 iphoneos-arm [installed,local]
gsc.displayport/now 1 iphoneos-arm [installed,local]
gsc.encode-aac/now 1 iphoneos-arm [installed,local]
gsc.encrypted-data-partition/now 1 iphoneos-arm [installed,local]
gsc.fcc-logos-via-software/now 1 iphoneos-arm [installed,local]
gsc.forward-camera-capability/now 1 iphoneos-arm [installed,local]
gsc.front-facing-camera/now 1 iphoneos-arm [installed,local]
gsc.gamekit/now 1 iphoneos-arm [installed,local]
gsc.gas-gauge-battery/now 1 iphoneos-arm [installed,local]
gsc.gps/now 1 iphoneos-arm [installed,local]
gsc.gyroscope/now 1 iphoneos-arm [installed,local]
gsc.hardware-keyboard/now 1 iphoneos-arm [installed,local]
gsc.has-baseband/now 1 iphoneos-arm [installed,local]
gsc.has-s-e-p/now 1 iphoneos-arm [installed,local]
gsc.has-spring-board/now 1 iphoneos-arm [installed,local]
gsc.has-thin-bezel/now 1 iphoneos-arm [installed,local]
gsc.hd-video-capture/now 1 iphoneos-arm [installed,local]
gsc.hdr-image-capture/now 1 iphoneos-arm [installed,local]
gsc.hidpi/now 1 iphoneos-arm [installed,local]
gsc.homescreen-wallpaper/now 1 iphoneos-arm [installed,local]
gsc.hw-encode-snapshots/now 1 iphoneos-arm [installed,local]
gsc.international-settings/now 1 iphoneos-arm [installed,local]
gsc.io-surface-backed-images/now 1 iphoneos-arm [installed,local]
gsc.load-thumbnails-while-scrolling/now 1 iphoneos-arm [installed,local]
gsc.location-services/now 1 iphoneos-arm [installed,local]
gsc.magnetometer/now 1 iphoneos-arm [installed,local]
gsc.main-screen-class/now 8 iphoneos-arm [installed,local]
gsc.main-screen-height/now 1334 iphoneos-arm [installed,local]
gsc.main-screen-pitch/now 326 iphoneos-arm [installed,local]
gsc.main-screen-scale/now 2 iphoneos-arm [installed,local]
gsc.main-screen-width/now 750 iphoneos-arm [installed,local]
gsc.microphone/now 1 iphoneos-arm [installed,local]
gsc.mms/now 1 iphoneos-arm [installed,local]
gsc.multitasking/now 1 iphoneos-arm [installed,local]
gsc.not-green-tea/now 1 iphoneos-arm [installed,local]
gsc.opengles-1/now 1 iphoneos-arm [installed,local]
gsc.opengles-2/now 1 iphoneos-arm [installed,local]
gsc.panorama-camera-capability/now 1 iphoneos-arm [installed,local]
gsc.peer-peer/now 1 iphoneos-arm [installed,local]
gsc.personal-hotspot/now 1 iphoneos-arm [installed,local]
gsc.photo-adjustments/now 1 iphoneos-arm [installed,local]
gsc.photo-stream/now 1 iphoneos-arm [installed,local]
gsc.proximity-sensor/now 1 iphoneos-arm [installed,local]
gsc.ptp-large-files/now 1 iphoneos-arm [installed,local]
gsc.rear-camera-capability/now 1 iphoneos-arm [installed,local]
gsc.rear-facing-camera/now 1 iphoneos-arm [installed,local]
gsc.regional-behavior-n-t-s-c/now 1 iphoneos-arm [installed,local]
gsc.ringer-switch/now 1 iphoneos-arm [installed,local]
gsc.shoebox/now 1 iphoneos-arm [installed,local]
gsc.signing-fuse/now 1 iphoneos-arm [installed,local]
gsc.sms/now 1 iphoneos-arm [installed,local]
gsc.stand-alone-contacts/now 1 iphoneos-arm [installed,local]
gsc.still-camera/now 1 iphoneos-arm [installed,local]
gsc.telephony/now 1 iphoneos-arm [installed,local]
gsc.tv-out-crossfade/now 1 iphoneos-arm [installed,local]
gsc.u-i-parallax-capability/now 1 iphoneos-arm [installed,local]
gsc.unified-ipod/now 1 iphoneos-arm [installed,local]
gsc.venice/now 1 iphoneos-arm [installed,local]
gsc.video-camera/now 1 iphoneos-arm [installed,local]
gsc.voice-control/now 1 iphoneos-arm [installed,local]
gsc.voip/now 1 iphoneos-arm [installed,local]
gsc.volume-buttons/now 1 iphoneos-arm [installed,local]
gsc.watch-companion/now 1 iphoneos-arm [installed,local]
gsc.wi-fi/now 1 iphoneos-arm [installed,local]
gsc.wifi/now 1 iphoneos-arm [installed,local]
gsc.youtube/now 1 iphoneos-arm [installed,local]
gzip/stable,now 1.8 iphoneos-arm [installed]
io.ijapija00.customcarrier/stable,now 1.3 iphoneos-arm [installed]
ldid/stable,now 2:1.2.2-coolstar iphoneos-arm [installed]
libassuan/stable,now 2.5.1 iphoneos-arm [installed]
libgpg-error/stable,now 1.27 iphoneos-arm [installed]
libksba/stable,now 1.3.5 iphoneos-arm [installed]
lzma/stable,now 5.2.3 iphoneos-arm [installed]
make/stable,now 4.2.1 iphoneos-arm [installed]
me.gmoran.eclipsex/stable,now 5.0b-229 iphoneos-arm [installed]
mobilesubstrate/stable,now 99.0 iphoneos-arm [installed]
nano/stable,now 2.9.1 iphoneos-arm [installed]
ncurses/stable,now 5.9 iphoneos-arm [installed]
npth/stable,now 1.5 iphoneos-arm [installed]
openssh/stable,now 7.6p1-4 iphoneos-arm [installed]
openssl/stable,now 1.0.2n iphoneos-arm [installed]
org.coolstar.tweakinject/now 1.0.4-1 iphoneos-arm [installed,local]
org.thebigboss.detailedbatteryusage/stable,now 1.1.1 iphoneos-arm [installed]
org.thebigboss.nudekeys/stable,now 3.1 iphoneos-arm [installed]
org.thebigboss.repo.icons/now 1.0 iphoneos-arm [installed,local]
p7zip/stable,now 16.02 iphoneos-arm [installed]
pincrush/stable,now 0.9.2-2 iphoneos-arm [installed]
preferenceloader/now 2.2.4~alpha1 iphoneos-arm [installed,local]
profile.d/now 0-2 iphoneos-arm [installed,local]
sed/stable,now 4.2.2 iphoneos-arm [installed]
shell-cmds/stable,now 203 iphoneos-arm [installed]
system-cmds/stable,now 790 iphoneos-arm [installed]
tar/stable,now 1.30 iphoneos-arm [installed]
uikittools/stable,now 1.1.12-coolstar iphoneos-arm [installed]
unrar/stable,now 5.5.8 iphoneos-arm [installed]
unzip/stable,now 6.0 iphoneos-arm [installed]
uuid/stable,now 1.6.2 iphoneos-arm [installed]
wget/stable,now 1.19 iphoneos-arm [installed]
zip/stable,now 3.0 iphoneos-arm [installed]
```

**Comment by dallasgroot** [comment]
when running apt-get upgrade via command line this is also what happens:

```
Dallass-iPhone:/deb root# apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  com.laughingquoll.noctisxi com.spark.taptickeys me.gmoran.eclipsex
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 892 kB of archives.
After this operation, 635 kB disk space will be freed.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  com.laughingquoll.noctisxi com.spark.taptickeys me.gmoran.eclipsex
Install these packages without verification? [y/N] y
Get:1 http://beta.sparkservers.co.uk ./ com.spark.taptickeys 3.0.3 [206 kB]
Err:2 https://beta.laughingquoll.net/repo ./ com.laughingquoll.noctisxi 1.0.8  
  HTTP/1.1 403 Not Authenticated
Get:3 https://gmoran.me/repo ./ me.gmoran.eclipsex 5.0b-235 [615 kB]
Fetched 822 kB in 0s (884 kB/s)         
W: No sandbox user '_apt' on the system, can not drop privileges
E: Failed to fetch https://beta.laughingquoll.net/repo/./debs/noctisxi.deb  HTTP/1.1 403 Not Authenticated
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by AppleBetas** [comment]
Here are my perms:

    /var/ 777
    /lib/ 755
    /apt/ 755
     /extended_states 644
     /lists 755
         /partial/ 755
     /mirrors/ 755
       /partial/ 755
    /periodic/ 755

I have a feeling its because your /var/lib/apt is 700, when mine is 755.

**Comment by dallasgroot** [comment]
I chmod 755 /var/lib/apt/lists/partial but still got the same errors, which is strange also because isn’t the apt directory created when cydia is launched and apt is activated?

**Comment by dallasgroot** [comment]
one more, what are your permissions for var/mobile/Library/Caches/com.saurik.Cydia? and inside... I know this is auto generated, but this is where the release files should be downloaded right? because this is what cydia is telling me
`Failed to fetch store:/var/mobile/Library/Caches/com.saurik.Cydia/lists/partial/....Packages.bz2 Hash mismatch Hashes of expected file: - Filesize 30839 [weak] - SHA(numbers and letters) - MD5Sum: (numbers and letters) Hashes of received file: - SHA(same numbers and letters) - MD5 (different numbers and letters) - Filesize:0 [weak] Last modification report: Mon 26 Feb 2018 23:50:57 +0000 Release file created at : <unknown>`

**Comment by AppleBetas** [comment]
com.saurik.Cydia: 755
      lists 755
        partial 700
          *.gpg 644

**Comment by dallasgroot** [comment]
Yeah I found out that isn’t the issue either... oh well, if I cannot get it it’s not the end of the world.

**Comment by dallasgroot** [comment]
Back again! 

So it appears its a Cydia issue and NOT APT. I'm able to install packages through apt command with the bundle identifier... 

```
Dallass-iPhone:~ root# apt-get install com.linusyang.localeutf8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  com.linusyang.localeutf8
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 5448 B of archives.
After this operation, 190 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  com.linusyang.localeutf8
Install these packages without verification? [y/N] y
Get:1 http://apt.thebigboss.org/repofiles/cydia stable/main iphoneos-arm com.linusyang.localeutf8 iphoneos-arm 1.0-1 [5448 B]
Fetched 5448 B in 0s (10.2 kB/s)             
Selecting previously unselected package com.linusyang.localeutf8.
(Reading database ... 4669 files and directories currently installed.)
Preparing to unpack .../com.linusyang.localeutf8_1.0-1_iphoneos-arm.deb ...
Unpacking com.linusyang.localeutf8 (1.0-1) ...
Setting up com.linusyang.localeutf8 (1.0-1) ...
Dallass-iPhone:~ root# apt-get install ws.hbang.common (>= 1.11.2)
-sh: syntax error near unexpected token `('
```

**Comment by dallasgroot** [comment]
@coolstar @AppleBetas I found the solution to my [problem](https://twitter.com/iamgroot11/status/974204259439820800): (now to figure out how to fix this so I don't need to do this work around)
