### ISSUE TITLE
Scripts cannot be run directly. (Shell Issue)

### ISSUE THREAD

**Issue by MCApollo** [ElectraJailbreak/electratools#27]
**If coolstar is going to ninja fix this, might as well ninja edit a thank you. FIXED in 4.4-1**

Codesigning seems to be blocking running scripts directly. Although it can be bypassed by telling bash to run it, honestly it’s a really bad workaround that might break somethings. (For example, maybe Theos?)

*example*

 >MC:~ root# echo "#!/bin/sh
 >echo Hello World" >> example.sh
MC:~ root# chmod +x example.sh
MC:~ root# ./example.sh
-sh: ./example.sh: /bin/sh: bad interpreter: Operation not permitted
MC:~ root# chmod 777 ./example.sh
MC:~ root# ./example.sh
-sh: ./example.sh: /bin/sh: bad interpreter: Operation not permitted
MC:~ root# bash !!
bash ./example.sh
Hello World
MC:~ root# ./example.sh
-sh: ./example.sh: /bin/sh: bad interpreter: Operation not permitted
MC:~ root# >

**Comment by notexe** [comment]
Scripts can be run directly if they do not have #! at the top declaring which language to run them in. The sandbox seems to block scripts that have #! at the top. Not sure if that can be patched or not.
