### ISSUE TITLE
Requesting whois

### ISSUE THREAD

**Issue by Favna** [ElectraJailbreak/electratools#3]
As the title says, it would be great if we can get `whois` along with the unix tools!

**Comment by notexe** [comment]
Curl is already included.

**Comment by Favna** [comment]
oh my bad. I was going on what is in the latest Electra build. Should've checked the debs dir. Edited title and original post.

![img](https://favna.s-ul.eu/xzsByH6m.png)

**Comment by coolstar** [comment]
whois is part of inetutils. Now available.
