### ISSUE TITLE
Find Utilities is broken

### ISSUE THREAD

**Issue by MCApollo** [ElectraJailbreak/electratools#34]
At configure time, prefix was set to /usr/local.
The package on the repo puts them at /usr.
This breaks updatedb and locate.

>updatedb needs to be able to execute /usr/local/bin/find, but cannot.
>updatedb needs to be able to execute /usr/local/libexec/frcode, but cannot.

**Comment by aassq115533** [comment]
https://github.com/ElectraJailbreak/electratools/commit/096b870f16d254747996a8780c99563a08420310#diff-0c11ef870a6a2e1594c222d07f2a6e3c
