### ISSUE TITLE
wget with ssl support 

### ISSUE THREAD

**Issue by ninoz** [ElectraJailbreak/electratools#8]
As per the title, currently we get:

root# which wget
/bootstrap/usr/local/bin/wget

root# wget https://www.google.com
--2018-02-11 11:07:51--  https://www.google.com/
Warning: This version of wget does not support SSL (J hasn't compiled OpenSSL for ARM..
Disabling SSL due to encountered errors.

**Comment by coolstar** [comment]
will be up soon

**Comment by coolstar** [comment]
wget with SSL now available

**Comment by DimPipal** [comment]
Excellent, thank you for all you work on this and Electra :)
