### ISSUE TITLE
cydo & su binary broken

### ISSUE THREAD

**Issue by jakeajames** [ElectraJailbreak/electratools#9]
When I try to execute those binaries they fail to communicate with jailbreakd. I get this error:

    event: <error: 0x1b0391dc0> { count = 1, transaction: 0, voucher = 0x0, contents =
       "XPCErrorDescription" => <string: 0x1b0392068> { length = 18, contents = "Connection invalid" }
    }

If I recompile them, they work properly, not sure what's causing it. Other binaries might be broken as well, but tried only these. Using latest Electra

**Comment by coolstar** [comment]
Working in latest packages + bootstrap
